export const dummyTestimonial = [
  {
    avatar: "/images/Ellipse 8 (4).png",
    name: "Wade Warren",
    time: "2 days ago",
    rate: 5,
    content: `TechUniverse NFTs have become a conversation starter and a symbol of forward-thinking in my circle. Displaying these NFTs in my digital art collection not only showcases my passion for technology but also sparks engaging discussions about the potential of emerging technologies and the impact  they will have on society. It's like having a  piece of the future on my digital wall.`,
  },
  {
    avatar: "/images/Ellipse 8 (5).png",
    name: "Leslie Alexander",
    time: "2 days ago",
    rate: 5,
    content: `Investing in TechUniverse NFTs was a no-brainer for me. The potential for real-world impact and the visionary appeal of these NFTs is unparalleled. I see these NFTs as not just digital assets, but as tangible representations of human ingenuity and innovation. I'm excited to see how these breakthrough concepts become a reality.`,
  },
  {
    avatar: "/images/Ellipse 8 (6).png",
    name: "Brooklyn Simmons",
    time: "2 days ago",
    rate: 5,
    content: `TechUniverse NFTs have become an integral part of my investment portfolio. The rapid pace of technological advancements can be overwhelming, but TechUniverse offers a curated collection of NFTs that allows me to engage with and understand the cutting-edge ideas and inventions that will shape our future. It's both thrilling and rewarding to be part of this technological journey.`,
  },
];

export const dummyActivities = [
  {
    activities: "Bid",
    title: "CinematicElegance",
    nft: "/images/Frame 2.png",
    owner: "From: Kristin Watson",
    price: "3.478 ETH",
    quantity: "1",
    time: "Yesterday 7:15pm",
  },
  {
    activities: "Purchased",
    title: "PixelPalette",
    nft: "/images/Frame 3.png",
    owner: "From: Webb",
    price: "5.9 ETH",
    quantity: "1",
    time: "6/7/2023 1:34pm",
  },
  {
    activities: "Minted",
    title: "PixelCouture",
    nft: "/images/Frame 4.png",
    price: "On bid",
    owner: "Owner",
    quantity: "1",
    time: "6/7/2023 1:34pm",
  },
  {
    activities: "Fractionally owned",
    title: "ChromaTracks",
    nft: "/images/Frame 5.png",
    price: "2.934 ETH",
    owner: "Fractional ownership",
    quantity: "1",
    time: "2/6/2023 3:12pm",
  },
  {
    activities: "Changed price",
    title: "ArtAlchemy",
    nft: "/images/Frame 6.png",
    price: "2.8 ETH",
    owner: "Owner",
    quantity: "1",
    time: "9/5/2023 9:09pm",
  },
];
